# Generated by Django 5.2.15 on 2026-06-16 16:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("cars", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ContactMessage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="الاسم")),
                (
                    "phone",
                    models.CharField(
                        blank=True, max_length=20, verbose_name="رقم الجوال"
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        blank=True, max_length=254, verbose_name="البريد الإلكتروني"
                    ),
                ),
                ("message", models.TextField(verbose_name="الرسالة")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("new", "جديد"),
                            ("contacted", "تم التواصل"),
                            ("closed", "مغلق"),
                        ],
                        default="new",
                        max_length=15,
                        verbose_name="الحالة",
                    ),
                ),
                (
                    "internal_note",
                    models.TextField(blank=True, verbose_name="ملاحظة داخلية"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "رسالة تواصل",
                "verbose_name_plural": "رسائل التواصل",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="InspectionRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="الاسم")),
                ("phone", models.CharField(max_length=20, verbose_name="رقم الجوال")),
                (
                    "preferred_time",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="الوقت المفضل"
                    ),
                ),
                ("note", models.TextField(blank=True, verbose_name="ملاحظة")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("new", "جديد"),
                            ("contacted", "تم التواصل"),
                            ("closed", "مغلق"),
                        ],
                        default="new",
                        max_length=15,
                        verbose_name="الحالة",
                    ),
                ),
                (
                    "internal_note",
                    models.TextField(blank=True, verbose_name="ملاحظة داخلية"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "car",
                    models.ForeignKey(
                        blank=True,
                        limit_choices_to={"car_type": "used"},
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="inspection_requests",
                        to="cars.car",
                        verbose_name="السيارة",
                    ),
                ),
            ],
            options={
                "verbose_name": "طلب معاينة",
                "verbose_name_plural": "طلبات المعاينة",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="TestDriveRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="الاسم")),
                ("phone", models.CharField(max_length=20, verbose_name="رقم الجوال")),
                (
                    "preferred_time",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="الوقت المفضل"
                    ),
                ),
                ("note", models.TextField(blank=True, verbose_name="ملاحظة")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("new", "جديد"),
                            ("contacted", "تم التواصل"),
                            ("closed", "مغلق"),
                        ],
                        default="new",
                        max_length=15,
                        verbose_name="الحالة",
                    ),
                ),
                (
                    "internal_note",
                    models.TextField(blank=True, verbose_name="ملاحظة داخلية"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "car",
                    models.ForeignKey(
                        blank=True,
                        limit_choices_to={"car_type": "new"},
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="test_drive_requests",
                        to="cars.car",
                        verbose_name="السيارة",
                    ),
                ),
            ],
            options={
                "verbose_name": "طلب تجربة قيادة",
                "verbose_name_plural": "طلبات تجربة القيادة",
                "ordering": ["-created_at"],
            },
        ),
    ]
