# Generated by Django 5.2.15 on 2026-06-16 16:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Branch",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="اسم الفرع")),
                ("city", models.CharField(max_length=100, verbose_name="المدينة")),
                ("address", models.TextField(blank=True, verbose_name="العنوان")),
                (
                    "phone",
                    models.CharField(blank=True, max_length=20, verbose_name="الهاتف"),
                ),
                (
                    "whatsapp",
                    models.CharField(blank=True, max_length=20, verbose_name="واتساب"),
                ),
            ],
            options={
                "verbose_name": "فرع",
                "verbose_name_plural": "الفروع",
                "ordering": ["city", "name"],
            },
        ),
        migrations.CreateModel(
            name="Brand",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=100, unique=True, verbose_name="الماركة"
                    ),
                ),
            ],
            options={
                "verbose_name": "ماركة",
                "verbose_name_plural": "الماركات",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Car",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "car_type",
                    models.CharField(
                        choices=[("new", "جديدة"), ("used", "مستعملة")],
                        max_length=10,
                        verbose_name="نوع السيارة",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("available", "متاحة"),
                            ("hidden", "مخفية"),
                            ("sold", "مباعة"),
                        ],
                        default="available",
                        max_length=10,
                        verbose_name="الحالة",
                    ),
                ),
                (
                    "model_name",
                    models.CharField(max_length=100, verbose_name="الموديل"),
                ),
                ("year", models.PositiveSmallIntegerField(verbose_name="السنة")),
                (
                    "price",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=12,
                        null=True,
                        verbose_name="السعر",
                    ),
                ),
                (
                    "price_label",
                    models.CharField(
                        blank=True,
                        help_text="مثال: ابتداءً من",
                        max_length=50,
                        verbose_name="تسمية السعر",
                    ),
                ),
                (
                    "trim",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="الفئة (Trim)"
                    ),
                ),
                (
                    "features_summary",
                    models.TextField(blank=True, verbose_name="مواصفات مختصرة"),
                ),
                (
                    "mileage_km",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="الممشى (كم)"
                    ),
                ),
                (
                    "transmission",
                    models.CharField(
                        blank=True,
                        choices=[("automatic", "أوتوماتيك"), ("manual", "يدوي")],
                        max_length=15,
                        verbose_name="ناقل الحركة",
                    ),
                ),
                (
                    "fuel_type",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("petrol", "بنزين"),
                            ("diesel", "ديزل"),
                            ("hybrid", "هجين"),
                            ("electric", "كهربائي"),
                        ],
                        max_length=15,
                        verbose_name="نوع الوقود",
                    ),
                ),
                (
                    "engine_size",
                    models.CharField(
                        blank=True, max_length=20, verbose_name="حجم المحرك"
                    ),
                ),
                (
                    "exterior_color",
                    models.CharField(
                        blank=True, max_length=50, verbose_name="اللون الخارجي"
                    ),
                ),
                (
                    "origin",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("saudi", "سعودي"),
                            ("gulf", "خليجي"),
                            ("imported", "مستورد"),
                        ],
                        max_length=15,
                        verbose_name="الوارد / المواصفات",
                    ),
                ),
                ("description", models.TextField(blank=True, verbose_name="وصف مختصر")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "branch",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="cars.branch",
                        verbose_name="الفرع / المدينة",
                    ),
                ),
                (
                    "brand",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="cars.brand",
                        verbose_name="الماركة",
                    ),
                ),
            ],
            options={
                "verbose_name": "سيارة",
                "verbose_name_plural": "السيارات",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="CarImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image", models.ImageField(upload_to="cars/", verbose_name="الصورة")),
                (
                    "is_main",
                    models.BooleanField(default=False, verbose_name="صورة رئيسية"),
                ),
                (
                    "order",
                    models.PositiveSmallIntegerField(default=0, verbose_name="الترتيب"),
                ),
                (
                    "car",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="images",
                        to="cars.car",
                        verbose_name="السيارة",
                    ),
                ),
            ],
            options={
                "verbose_name": "صورة سيارة",
                "verbose_name_plural": "صور السيارات",
                "ordering": ["-is_main", "order"],
            },
        ),
    ]
