# Generated by Django 5.2.15 on 2026-06-16 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cars", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="car",
            name="branch",
        ),
        migrations.AddField(
            model_name="car",
            name="city",
            field=models.CharField(blank=True, max_length=100, verbose_name="المدينة"),
        ),
        migrations.DeleteModel(
            name="Branch",
        ),
    ]
